export const ALLEVENTS = 'events/ALLEVENTS'
export const ADDEVENT = 'events/ADDEVENT'
export const CAROUSEL = 'events/CAROUSEL'
export const MOREEVENTS = 'events/MOREEVENTS'
export const NEXTEVENTS = 'events/NEXTEVENTS'
export const CHANGEEVENT = 'events/CHANGEEVENT'
